- name: set hostname
  ansible.builtin.hostname:
    name: vps.e-bpf.com
    use: systemd

- name: localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 localhost.localdomain localhost

- name: vps.e-bpf.com
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: '{{ host_ip }} vps.e-bpf.com vps'
