- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart iptables
  ansible.builtin.systemd:
    name: iptables
    state: restarted

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
