- name: install packages
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - lxc
      - arch-install-scripts

- name: default.conf
  ansible.builtin.template:
    src: templates/default.conf.j2
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: '644'

- name: backups directory
  ansible.builtin.file:
    path: /mnt/storage/backups/lxc
    owner: root
    group: root
    mode: '700'
    state: directory
