- name: netdev
  ansible.builtin.copy:
    src: files/br0.netdev
    dest: /etc/systemd/network/br0.netdev
    owner: root
    group: root
    mode: '644'
  notify: restart systemd-networkd

- name: network
  ansible.builtin.copy:
    src: files/br0.network
    dest: /etc/systemd/network/br0.network
    owner: root
    group: root
    mode: '644'
  notify: restart systemd-networkd
