---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- dev:
    - Github:
        - abbr: GH
          icon: github.svg
          href: https://github.com/tyrone-wu
